In [5]:
from google.colab import files

In [6]:
import pandas as pd
import numpy as np
import seaborn as sns

In [10]:
print(np.eye(3))
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [7]:
file_url = "https://raw.githubusercontent.com/WalePhenomenon/climate_change/master/fuel_ferc1.csv"

df = pd.read_csv(file_url)

In [8]:
df.head()

record_id  ...  fuel_cost_per_mmbtu
0   f1_fuel_1994_12_1_0_7  ...                1.121
1  f1_fuel_1994_12_1_0_10  ...                1.120
2   f1_fuel_1994_12_2_0_1  ...                1.650
3   f1_fuel_1994_12_2_0_7  ...                1.970
4  f1_fuel_1994_12_2_0_10  ...                2.570

[5 rows x 11 columns]

In [12]:
df.groupby(df['fuel_type_code_pudl'])['fuel_cost_per_unit_burned'].mean().min()

13.659396569737135

In [14]:
df_fuel_mmbu = df['fuel_mmbtu_per_unit'].to_frame()
df_fuel_mmbu.head()

fuel_mmbtu_per_unit
0               16.590
1               16.592
2               24.130
3               23.950
4                1.000

In [15]:
df_fuel_mmbu.describe()

fuel_mmbtu_per_unit
count         29523.000000
mean              8.492111
std              10.600220
min               0.000001
25%               1.024000
50%               5.762694
75%              17.006000
max             341.260000

In [19]:
df['fuel_qty_burned'].corr

<bound method Series.corr of 0         5377489.0
1        10486945.0
2         2978683.0
3         3739484.0
4           40533.0
            ...    
29518       18799.0
29519      806730.0
29520      104554.0
29521      315945.0
29522       17853.0
Name: fuel_qty_burned, Length: 29523, dtype: float64>

In [23]:
df.groupby(df['report_year'])['fuel_cost_per_unit_delivered'].mean()

report_year
1994       63.636060
1995       32.735269
1996     9196.705948
1997    11140.197239
1998      287.154420
1999       25.551627
2000      985.362877
2001       60.050396
2002       47.594361
2003       55.663493
2004      139.524275
2005       41.438184
2006       38.657484
2007       43.325023
2008       58.588197
2009      652.694163
2010       91.862105
2011       59.774667
2012       60.994502
2013      172.307591
2014      192.737183
2015      326.535511
2016      103.901761
2017       46.196861
2018      499.269966
Name: fuel_cost_per_unit_delivered, dtype: float64

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29523 entries, 0 to 29522
Data columns (total 11 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   record_id                     29523 non-null  object 
 1   utility_id_ferc1              29523 non-null  int64  
 2   report_year                   29523 non-null  int64  
 3   plant_name_ferc1              29523 non-null  object 
 4   fuel_type_code_pudl           29523 non-null  object 
 5   fuel_unit                     29343 non-null  object 
 6   fuel_qty_burned               29523 non-null  float64
 7   fuel_mmbtu_per_unit           29523 non-null  float64
 8   fuel_cost_per_unit_burned     29523 non-null  float64
 9   fuel_cost_per_unit_delivered  29523 non-null  float64
 10  fuel_cost_per_mmbtu           29523 non-null  float64
dtypes: float64(5), int64(2), object(4)
memory usage: 2.5+ MB


In [25]:
df.describe(include='all')

record_id  ...  fuel_cost_per_mmbtu
count                     29523  ...         29523.000000
unique                    29523  ...                  NaN
top     f1_fuel_2010_12_281_3_1  ...                  NaN
freq                          1  ...                  NaN
mean                        NaN  ...            19.304354
std                         NaN  ...          2091.540939
min                         NaN  ...           -41.501000
25%                         NaN  ...             1.940000
50%                         NaN  ...             4.127000
75%                         NaN  ...             7.745000
max                         NaN  ...        359278.000000

[11 rows x 11 columns]

In [26]:
df.isnull().sum()

record_id                         0
utility_id_ferc1                  0
report_year                       0
plant_name_ferc1                  0
fuel_type_code_pudl               0
fuel_unit                       180
fuel_qty_burned                   0
fuel_mmbtu_per_unit               0
fuel_cost_per_unit_burned         0
fuel_cost_per_unit_delivered      0
fuel_cost_per_mmbtu               0
dtype: int64

In [28]:
df.shape

(29523, 11)

In [30]:
percent_of_missing_row = (180/df.shape[0]) * 100
print(percent_of_missing_row)

0.609694136774718


In [34]:
df.corr

<bound method DataFrame.corr of                      record_id  ...  fuel_cost_per_mmbtu
0        f1_fuel_1994_12_1_0_7  ...                1.121
1       f1_fuel_1994_12_1_0_10  ...                1.120
2        f1_fuel_1994_12_2_0_1  ...                1.650
3        f1_fuel_1994_12_2_0_7  ...                1.970
4       f1_fuel_1994_12_2_0_10  ...                2.570
...                        ...  ...                  ...
29518  f1_fuel_2018_12_12_0_13  ...                9.030
29519   f1_fuel_2018_12_12_1_1  ...                6.950
29520  f1_fuel_2018_12_12_1_10  ...                8.990
29521  f1_fuel_2018_12_12_1_13  ...                1.110
29522  f1_fuel_2018_12_12_1_14  ...               11.680

[29523 rows x 11 columns]>

In [38]:
df['coal'] = df['fuel_type_code_pudl'] == 'coal'
df['coal'].head()

0     True
1     True
2     True
3     True
4    False
Name: coal, dtype: bool